# Generated by Django 4.1.3 on 2022-11-30 00:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('name_en', models.CharField(max_length=64, unique=True)),
                ('name_ar', models.CharField(max_length=64, unique=True)),
                ('ayas', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(286), django.core.validators.MinValueValidator(3)])),
                ('number', models.PositiveSmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(114), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(choices=[('AT', 'Attended'), ('MI', 'Missed'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_aya', models.PositiveSmallIntegerField()),
                ('to_aya', models.PositiveSmallIntegerField()),
                ('type', models.CharField(choices=[('HI', 'Hivz'), ('RE', 'Revision')], default='HI', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='progress.session')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='progress.surah')),
            ],
        ),
    ]
